apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          env:
            - name: PMA_HOST
              value: "mysql"  # Connects to MySQL inside Kubernetes
            - name: PMA_PORT
              value: "3306"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: NodePort  # Exposes phpMyAdmin on a high port
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Change this if needed (must be between 30000-32767)
